# Pleasese make sure to update the license_key information with the license key for your New Relic
# account.
#
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: ''
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1
#
# Agent Configuration:
#
host:
    host: 127.0.0.1
    port: 11300

agents:
  queues:
      -
         name: request
      -
         name: export
      -
         name: config
      -
  
